# Copyright 2014 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Like Hello world, but built with Pants.

python_binary(
  name='main',
  dependencies=[
    '3rdparty/python:gitpython',
    '3rdparty/python:pyyaml',
    '3rdparty/python:travispy',
  ],
  source='exploit_travis.py',
)